version: '3.8'

services:
  postgres:
    image: postgres:14.4-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  app:
    build:
      context: .
    environment:
      - APP_HOST=localhost:80
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
